
import { PageHeader } from '../components/ui/PageHeader';
import { Panel } from '../components/ui/Panel';
import { ShieldCheck, Info, AlertTriangle, Lock } from 'lucide-react';

export function SecurityCenter() {
  return (
    <div className="space-y-6">
      <PageHeader 
        title="Safety & Security Center" 
        description="Understanding the boundaries and safety mechanisms of CyberShadow."
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Panel className="border-cyan-900 bg-cyan-950/10">
            <h2 className="text-xl font-bold text-cyan-400 mb-4 flex items-center gap-2">
              <ShieldCheck />
              Core Safety Principles
            </h2>
            <div className="space-y-4 text-gray-300">
              <p className="leading-relaxed">
                <strong className="text-white">CyberShadow uses fictional digital identities and simulated attack scenarios.</strong> 
                It is designed strictly as an educational and analytical tool to understand cybersecurity dynamics.
              </p>
              <p className="leading-relaxed">
                <strong className="text-white">CyberShadow does not attack, scan, exploit, or access real systems.</strong> 
                All simulations occur within an isolated mathematical model and do not generate actual network traffic or interact with external services.
              </p>
            </div>
          </Panel>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Panel>
              <div className="text-amber-500 mb-4">
                <AlertTriangle size={32} />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">Simulation Only</h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                Metrics, paths, and outcomes displayed in CyberShadow are generated by a simulation engine. They represent hypothetical scenarios and do not guarantee real-world security or imply actual vulnerabilities in your systems.
              </p>
            </Panel>
            
            <Panel>
              <div className="text-green-500 mb-4">
                <Lock size={32} />
              </div>
              <h3 className="text-lg font-bold text-white mb-2">No Real Credentials</h3>
              <p className="text-sm text-gray-400 leading-relaxed">
                CyberShadow operates using synthetic data models. It never requires, requests, or stores real passwords, tokens, or live authentication credentials.
              </p>
            </Panel>
          </div>
        </div>

        <div className="space-y-6">
          <Panel>
            <div className="text-cyan-500 mb-4">
              <Info size={24} />
            </div>
            <h3 className="text-lg font-bold text-white mb-2">Environment Status</h3>
            <div className="space-y-3 mt-4">
              <div className="flex justify-between items-center py-2 border-b border-gray-800">
                <span className="text-sm text-gray-400">Simulation Engine</span>
                <span className="text-xs font-medium text-cyan-400 bg-cyan-900/30 px-2 py-1 rounded">ISOLATED</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-gray-800">
                <span className="text-sm text-gray-400">External Network</span>
                <span className="text-xs font-medium text-green-400 bg-green-900/30 px-2 py-1 rounded">DISCONNECTED</span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-sm text-gray-400">Data Model</span>
                <span className="text-xs font-medium text-violet-400 bg-violet-900/30 px-2 py-1 rounded">SYNTHETIC ONLY</span>
              </div>
            </div>
          </Panel>
        </div>
      </div>
    </div>
  );
}
